-- Generated from shared/src/manzil_shared/catalog.py — never edit by hand.
-- Regenerate: uv run --package manzil-shared python -m manzil_shared.catalog

insert into criteria_catalog
  (key, label, category, domain, value_schema, default_options, extraction_hint, requires_tool, refresh_class)
values
  ('beds', 'Number of bedrooms', 'unit', 'rent', '{"type": "integer", "minimum": 0, "maximum": 5}'::jsonb, '[{"match": {"op": "eq", "value": 2}, "delta": 0.5}, {"match": {"op": "eq", "value": 1}, "delta": 0.0}, {"match": {"op": "eq", "value": 0}, "delta": -0.5}]'::jsonb, 'Count distinct bedrooms; a studio is 0.', null, 'listing_details'),
  ('baths', 'Number of bathrooms', 'unit', 'rent', '{"type": "number", "minimum": 1, "maximum": 4, "multipleOf": 0.5}'::jsonb, '[{"match": {"op": "gt", "value": 1.5}, "delta": 0.5}, {"match": {"op": "eq", "value": 1.5}, "delta": 0.25}, {"match": {"op": "eq", "value": 1}, "delta": 0.0}]'::jsonb, 'Count bathrooms; a half bath (no shower/tub) counts 0.5.', null, 'listing_details'),
  ('sqft', 'Square footage', 'unit', 'rent', '{"type": "integer", "minimum": 0}'::jsonb, '[{"match": {"op": "gt", "value": 900}, "delta": 0.5}, {"match": {"op": "range", "value": [700, 900]}, "delta": 0.0}, {"match": {"op": "lt", "value": 700}, "delta": -0.5}]'::jsonb, 'Interior area of the unit in square feet.', null, 'listing_details'),
  ('patio_balcony', 'Patio or balcony', 'unit', 'rent', '{"type": "boolean"}'::jsonb, '[{"match": {"op": "bool", "value": true}, "delta": 0.5}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True if the unit has a private patio or balcony.', null, 'listing_details'),
  ('private_entry', 'Private entrance', 'unit', 'rent', '{"type": "boolean"}'::jsonb, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True if the unit has its own exterior entrance rather than a shared interior corridor.', null, 'listing_details'),
  ('in_unit_laundry', 'Laundry', 'unit', 'rent', '{"type": "string", "enum": ["in_unit", "hookups", "on_site", "none"]}'::jsonb, '[{"match": {"op": "eq", "value": "in_unit"}, "delta": 1.0}, {"match": {"op": "eq", "value": "hookups"}, "delta": 0.25}, {"match": {"op": "eq", "value": "on_site"}, "delta": -0.5}, {"match": {"op": "eq", "value": "none"}, "delta": -1.0}]'::jsonb, 'in_unit = washer/dryer inside the unit; hookups = connections only; on_site = shared laundry room/facilities; none otherwise.', null, 'listing_details'),
  ('pets_policy', 'Pets policy', 'policy', 'rent', '{"type": "string", "enum": ["cats_and_dogs", "cats_only", "dogs_only", "none"]}'::jsonb, '[{"match": {"op": "eq", "value": "cats_and_dogs"}, "delta": 0.5}, {"match": {"op": "eq", "value": "cats_only"}, "delta": 0.25}, {"match": {"op": "eq", "value": "dogs_only"}, "delta": 0.0}, {"match": {"op": "eq", "value": "none"}, "delta": -0.5}]'::jsonb, 'Which pets the policy allows, ignoring breed and weight limits.If a fee is mentioned for a pet, then we can consider it a pet policy criterion.', null, 'listing_details'),
  ('all_in_monthly', 'All-in monthly cost', 'cost', 'rent', '{"type": "number", "minimum": 0}'::jsonb, '[{"match": {"op": "lt", "value": 1800}, "delta": 1.0}, {"match": {"op": "range", "value": [1800, 2000]}, "delta": 0.5}, {"match": {"op": "range", "value": [2000, 2200]}, "delta": 0.0}, {"match": {"op": "gt", "value": 2200}, "delta": -1.0}]'::jsonb, 'Composed by the pipeline from rent, mandatory fees, pet costs, and utility estimates (DESIGN §9.5) — never extracted directly from the page.', null, 'pricing'),
  ('security_deposit', 'Security deposit', 'cost', 'rent', '{"type": "number", "minimum": 0}'::jsonb, '[{"match": {"op": "lt", "value": 500}, "delta": 0.25}, {"match": {"op": "range", "value": [500, 1000]}, "delta": 0.0}, {"match": {"op": "gt", "value": 1000}, "delta": -0.25}]'::jsonb, 'Refundable security deposit in dollars; use the standard amount, not a promotional one.', null, 'pricing'),
  ('availability_date', 'Availability date', 'availability', 'rent', '{"type": "string", "format": "date"}'::jsonb, '[]'::jsonb, 'Earliest stated move-in date for the unit, as an ISO date (YYYY-MM-DD). Search prose and [EMBEDDED DATA]. If the target Property/Floor Plan has an explicit availability date, emit the earliest explicit ISO date even when the UI also says ''Available Now'', ''Now'', or ''Immediately''. Emit the literal sentinel available_now only when that target has immediate wording and no explicit availability date — never invent a calendar date. Ignore similar/nearby Properties, page update timestamps, promotions, and unrelated dates. Property-level availability is the earliest relevant date across the target Property''s plans. The pipeline rewrites available_now to the run date (live) or corpus saved_at date (bench).', null, 'pricing'),
  ('kitchen_quality', 'Kitchen quality', 'condition', 'rent', '{"type": "integer", "minimum": 1, "maximum": 5}'::jsonb, '[{"match": {"op": "gt", "value": 3}, "delta": 0.5}, {"match": {"op": "eq", "value": 3}, "delta": 0.0}, {"match": {"op": "lt", "value": 3}, "delta": -0.5}]'::jsonb, '1-5 rating assessed by VISION from listing photos against the anchored reference set (DESIGN §10.8), not from text.', 'vision', 'images'),
  ('flooring_quality', 'Flooring quality', 'condition', 'rent', '{"type": "integer", "minimum": 1, "maximum": 5}'::jsonb, '[{"match": {"op": "gt", "value": 3}, "delta": 0.5}, {"match": {"op": "eq", "value": 3}, "delta": 0.0}, {"match": {"op": "lt", "value": 3}, "delta": -0.5}]'::jsonb, '1-5 rating of floor/carpet condition assessed by VISION from listing photos against the anchored reference set, not from text.', 'vision', 'images'),
  ('parking', 'Parking', 'unit', 'rent', '{"type": "string", "enum": ["garage", "carport", "dedicated_lot", "street_only", "none"]}'::jsonb, '[{"match": {"op": "eq", "value": "garage"}, "delta": 0.5}, {"match": {"op": "eq", "value": "carport"}, "delta": 0.25}, {"match": {"op": "eq", "value": "dedicated_lot"}, "delta": 0.0}, {"match": {"op": "eq", "value": "street_only"}, "delta": -0.5}, {"match": {"op": "eq", "value": "none"}, "delta": -1.0}]'::jsonb, 'Best parking included or available with the unit: garage, carport, dedicated_lot (assigned or off-street lot), street_only, or none.', null, 'listing_details'),
  ('cooling', 'Cooling', 'unit', 'rent', '{"type": "string", "enum": ["central", "window_units", "none"]}'::jsonb, '[{"match": {"op": "eq", "value": "central"}, "delta": 0.5}, {"match": {"op": "eq", "value": "window_units"}, "delta": 0.0}, {"match": {"op": "eq", "value": "none"}, "delta": -1.0}]'::jsonb, 'central = central air conditioning; window_units = window/wall units provided or explicitly permitted; none otherwise.', null, 'listing_details'),
  ('dishwasher', 'Dishwasher', 'unit', 'rent', '{"type": "boolean"}'::jsonb, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True if the unit includes a dishwasher.', null, 'listing_details'),
  ('min_lease_months', 'Minimum lease term', 'policy', 'rent', '{"type": "integer", "minimum": 1}'::jsonb, '[{"match": {"op": "lt", "value": 12}, "delta": 0.25}, {"match": {"op": "eq", "value": 12}, "delta": 0.0}, {"match": {"op": "gt", "value": 12}, "delta": -0.5}]'::jsonb, 'Shortest lease term offered, in months; month-to-month is 1.', null, 'pricing'),
  ('grocery_proximity', 'Grocery proximity', 'location', 'rent', '{"type": "number", "minimum": 0}'::jsonb, '[{"match": {"op": "lt", "value": 10}, "delta": 0.5}, {"match": {"op": "range", "value": [10, 20]}, "delta": 0.0}, {"match": {"op": "gt", "value": 20}, "delta": -0.5}]'::jsonb, 'Minutes to the nearest full grocery store, walking or driving per the hunt setting; computed via Maps, not extracted from the page.', 'maps', 'location'),
  ('management_reviews', 'Management reviews', 'reputation', 'rent', '{"type": "object", "properties": {"rating": {"type": "number", "minimum": 1, "maximum": 5}, "summary": {"type": "string"}}, "required": ["rating"]}'::jsonb, '[{"match": {"op": "gt", "value": 4}, "delta": 0.5}, {"match": {"op": "range", "value": [3, 4]}, "delta": 0.0}, {"match": {"op": "lt", "value": 3}, "delta": -0.5}]'::jsonb, 'Aggregate review rating (1-5) plus a short reputation summary, sourced from Places reviews.', 'maps', 'reviews'),
  ('location_safety', 'Location safety', 'location', 'rent', '{"type": "string", "enum": ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F"]}'::jsonb, '[{"match": {"op": "eq", "value": "A+"}, "delta": 0.5}, {"match": {"op": "eq", "value": "A"}, "delta": 0.5}, {"match": {"op": "eq", "value": "A-"}, "delta": 0.5}, {"match": {"op": "eq", "value": "B+"}, "delta": 0.25}, {"match": {"op": "eq", "value": "B"}, "delta": 0.25}, {"match": {"op": "eq", "value": "B-"}, "delta": 0.25}, {"match": {"op": "eq", "value": "C+"}, "delta": 0.0}, {"match": {"op": "eq", "value": "C"}, "delta": 0.0}, {"match": {"op": "eq", "value": "C-"}, "delta": 0.0}, {"match": {"op": "eq", "value": "D+"}, "delta": -0.5}, {"match": {"op": "eq", "value": "D"}, "delta": -0.5}, {"match": {"op": "eq", "value": "D-"}, "delta": -0.5}, {"match": {"op": "eq", "value": "F"}, "delta": -1.0}]'::jsonb, 'Letter-grade location safety (A+ through F). Placeholder in v1: no pipeline stage emits it — the value arrives via human override until the dedicated safety module (DESIGN §18, P3-17) lands. Inherently low-confidence by design (DESIGN R8) — frame as such, never as fact.', 'web_search', 'reviews')
on conflict (key) do update set
  label = excluded.label,
  category = excluded.category,
  domain = excluded.domain,
  value_schema = excluded.value_schema,
  default_options = excluded.default_options,
  extraction_hint = excluded.extraction_hint,
  requires_tool = excluded.requires_tool,
  refresh_class = excluded.refresh_class;
