"""Visit lifecycle and unit endpoints (VC-1, DESIGN §9.7, §4.2)."""

from __future__ import annotations

import pytest
from httpx import AsyncClient
from manzil_api.visits.template import TEMPLATE_VERSION


async def _create(client: AsyncClient, collab_hunt, **overrides):  # type: ignore[no-untyped-def]
    payload = {"property_id": collab_hunt["owner_property_id"], **overrides}
    return await client.post(f"/v1/hunts/{collab_hunt['hunt_id']}/visits", json=payload)


@pytest.mark.asyncio
async def test_create_visit_spanning_a_planned_and_a_described_unit(
    collab_hunt, as_member: AsyncClient
) -> None:
    created = await _create(
        as_member,
        collab_hunt,
        units=[
            # Backed by a Floor Plan: beds/baths come from the plan, so the Unit
            # Group key matches the listing's own grouping.
            {"label": "4B", "floor_plan_id": collab_hunt["owner_plan_id"], "display_order": 0},
            # A unit the listing never advertised — the normal case, not an error.
            {"label": "the corner one", "beds": 1, "baths": 1.5, "display_order": 1},
        ],
    )
    assert created.status_code == 201, created.text
    body = created.json()
    assert body["state"] == "planned"
    assert body["template_version"] == TEMPLATE_VERSION
    assert body["started_at"] is None

    units = {unit["label"]: unit for unit in body["units"]}
    # Derived by the database from the Floor Plan's own beds/baths, so the key
    # matches the listing's grouping rather than anything the client sent.
    assert units["4B"]["unit_group_key"] == "1-1"
    assert units["4B"]["floor_plan_id"] == collab_hunt["owner_plan_id"]
    # Generated by the database, and normalized: 1.5 baths stays "1-1.5" while a
    # whole number must not become "1-1.0" or the roll-up joins nothing.
    assert units["the corner one"]["unit_group_key"] == "1-1.5"
    assert units["the corner one"]["floor_plan_id"] is None


@pytest.mark.asyncio
async def test_whole_number_baths_normalize_without_a_trailing_zero(
    collab_hunt, as_member: AsyncClient
) -> None:
    created = await _create(as_member, collab_hunt, units=[{"label": "2A", "beds": 2, "baths": 2}])
    assert created.status_code == 201
    assert created.json()["units"][0]["unit_group_key"] == "2-2"


@pytest.mark.asyncio
async def test_property_must_be_in_this_hunt(collab_hunt, as_member: AsyncClient, db_pool) -> None:
    foreign_property = await db_pool.fetchval(
        "insert into properties (name, canonical_address) "
        "values ('Elsewhere', '9 Nowhere') returning id"
    )
    try:
        response = await _create(as_member, collab_hunt, property_id=str(foreign_property))
        assert response.status_code == 422
        assert response.json()["code"] == "property_not_in_hunt"
    finally:
        await db_pool.execute("delete from properties where id = $1", foreign_property)


@pytest.mark.asyncio
async def test_floor_plan_from_another_property_is_refused(
    collab_hunt, as_member: AsyncClient
) -> None:
    response = await _create(
        as_member,
        collab_hunt,
        units=[{"label": "4B", "floor_plan_id": collab_hunt["member_plan_id"]}],
    )
    assert response.status_code == 422
    assert response.json()["code"] == "floor_plan_not_on_property"


@pytest.mark.asyncio
async def test_unit_needs_a_plan_or_a_typed_shape(collab_hunt, as_member: AsyncClient) -> None:
    response = await _create(as_member, collab_hunt, units=[{"label": "mystery"}])
    assert response.status_code == 422


@pytest.mark.asyncio
async def test_duplicate_unit_labels_are_refused(collab_hunt, as_member: AsyncClient) -> None:
    both_at_once = await _create(
        as_member,
        collab_hunt,
        units=[
            {"label": "4B", "beds": 2, "baths": 2},
            {"label": "4b", "beds": 2, "baths": 2},
        ],
    )
    assert both_at_once.status_code == 422

    created = await _create(as_member, collab_hunt, units=[{"label": "4B", "beds": 2, "baths": 2}])
    visit_id = created.json()["id"]
    clash = await as_member.post(
        f"/v1/visits/{visit_id}/units", json={"label": " 4B ", "beds": 2, "baths": 2}
    )
    assert clash.status_code == 409
    assert clash.json()["code"] == "duplicate_visit_unit_label"


@pytest.mark.asyncio
async def test_lifecycle_start_end_and_derived_state(collab_hunt, as_member: AsyncClient) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]

    too_early = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "end"})
    assert too_early.status_code == 409
    assert too_early.json()["code"] == "invalid_visit_transition"

    started = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    assert started.status_code == 200
    assert started.json()["state"] == "in_progress"
    assert started.json()["started_at"] is not None

    # Starting twice is idempotent: the tour began when it began.
    again = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    assert again.json()["started_at"] == started.json()["started_at"]

    ended = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "end"})
    assert ended.status_code == 200
    assert ended.json()["state"] == "completed"


@pytest.mark.asyncio
async def test_cancellation_outranks_a_started_tour(collab_hunt, as_member: AsyncClient) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    cancelled = await as_member.patch(
        f"/v1/visits/{visit_id}", json={"action": "cancel", "cancel_reason": "agent no-showed"}
    )
    assert cancelled.status_code == 200
    body = cancelled.json()
    assert body["state"] == "cancelled"
    assert body["started_at"] is not None, "the tour did start; cancellation does not erase that"
    assert body["cancel_reason"] == "agent no-showed"


@pytest.mark.asyncio
async def test_cancel_narrows_to_creator_or_owner(
    collab_hunt, as_member: AsyncClient, as_curator: AsyncClient, as_owner: AsyncClient
) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]

    # A Curator is not the creator: cancelling someone else's visit is not theirs
    # to do, even though they may answer every item on it (DESIGN §4.2).
    denied = await as_curator.patch(f"/v1/visits/{visit_id}", json={"action": "cancel"})
    assert denied.status_code == 403
    assert denied.json()["code"] == "cannot_cancel_visit"

    # The Owner may.
    cancelled = await as_owner.patch(f"/v1/visits/{visit_id}", json={"action": "cancel"})
    assert cancelled.status_code == 200

    reinstated = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "reinstate"})
    assert reinstated.status_code == 200
    assert reinstated.json()["state"] == "planned"


@pytest.mark.asyncio
async def test_start_is_refused_while_cancelled(collab_hunt, as_member: AsyncClient) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "cancel"})
    blocked = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    assert blocked.status_code == 409


@pytest.mark.asyncio
async def test_any_member_may_start_someone_elses_visit(
    collab_hunt, as_member: AsyncClient, as_curator: AsyncClient
) -> None:
    """Whoever arrives first starts the tour — that is the point of a shared visit."""
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    started = await as_curator.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    assert started.status_code == 200
    assert started.json()["state"] == "in_progress"


@pytest.mark.asyncio
async def test_delete_narrows_to_creator_or_owner(
    collab_hunt, as_member: AsyncClient, as_curator: AsyncClient
) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    denied = await as_curator.delete(f"/v1/visits/{visit_id}")
    assert denied.status_code == 403
    deleted = await as_member.delete(f"/v1/visits/{visit_id}")
    assert deleted.status_code == 204
    gone = await as_member.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    assert gone.status_code == 404


@pytest.mark.asyncio
async def test_reschedule_and_unit_crud(collab_hunt, as_member: AsyncClient) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]

    moved = await as_member.patch(
        f"/v1/visits/{visit_id}",
        json={"action": "reschedule", "scheduled_for": "2026-08-04T15:30:00Z"},
    )
    assert moved.status_code == 200
    assert moved.json()["scheduled_for"].startswith("2026-08-04T15:30:00")

    added = await as_member.post(
        f"/v1/visits/{visit_id}/units",
        json={"label": "basement 2br", "beds": 2, "baths": 3},
    )
    assert added.status_code == 201
    unit = added.json()
    assert unit["unit_group_key"] == "2-3"

    renamed = await as_member.patch(
        f"/v1/visits/{visit_id}/units/{unit['id']}", json={"label": "Unit B1"}
    )
    assert renamed.status_code == 200
    assert renamed.json()["label"] == "Unit B1"

    removed = await as_member.delete(f"/v1/visits/{visit_id}/units/{unit['id']}")
    assert removed.status_code == 204
    twice = await as_member.delete(f"/v1/visits/{visit_id}/units/{unit['id']}")
    assert twice.status_code == 404


@pytest.mark.asyncio
async def test_custom_item_is_recorded_against_the_visit(
    collab_hunt, as_member: AsyncClient
) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    created = await as_member.post(
        f"/v1/visits/{visit_id}/custom-items",
        json={
            "section_key": "kitchen",
            "kind": "check",
            "scope": "unit",
            "label": "Room for the stand mixer",
        },
    )
    assert created.status_code == 201
    assert created.json()["label"] == "Room for the stand mixer"
    assert created.json()["visit_id"] == visit_id


@pytest.mark.asyncio
async def test_outsider_cannot_see_or_touch_a_visit(
    collab_hunt, as_member: AsyncClient, as_outsider: AsyncClient
) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    # 404 rather than 403: confirming the Visit exists would leak a Hunt the
    # caller cannot see.
    assert (
        await as_outsider.patch(f"/v1/visits/{visit_id}", json={"action": "start"})
    ).status_code == 404
    assert (await as_outsider.delete(f"/v1/visits/{visit_id}")).status_code == 404
    denied = await as_outsider.post(
        f"/v1/hunts/{collab_hunt['hunt_id']}/visits",
        json={"property_id": collab_hunt["owner_property_id"]},
    )
    assert denied.status_code in (403, 404)


@pytest.mark.asyncio
async def test_patch_requires_something_to_do(collab_hunt, as_member: AsyncClient) -> None:
    visit_id = (await _create(as_member, collab_hunt)).json()["id"]
    empty = await as_member.patch(f"/v1/visits/{visit_id}", json={})
    assert empty.status_code == 422


@pytest.mark.asyncio
async def test_reopening_a_finished_visit_makes_it_editable_again(
    collab_hunt, as_owner: AsyncClient
) -> None:
    """Ending is a state, not a seal (DESIGN §9.7).

    A tour is written on a phone and read on a desktop, and the desktop is where
    the typo gets fixed and the half-heard answer finally gets typed.
    """
    visit = (await _create(as_owner, collab_hunt)).json()
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "start"})
    ended = await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "end"})
    assert ended.json()["state"] == "completed"

    reopened = await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "reopen"})
    assert reopened.status_code == 200, reopened.text
    assert reopened.json()["state"] == "in_progress"
    # VC-9: the tour ended when it ended. Reopening records a *second* event
    # rather than erasing the first, so the 42 minutes it actually took survives.
    assert reopened.json()["ended_at"] == ended.json()["ended_at"]
    assert reopened.json()["reopened_at"] is not None
    # The tour still knows when it started; reopening is not restarting.
    assert reopened.json()["started_at"] is not None


@pytest.mark.asyncio
async def test_any_member_may_reopen(
    collab_hunt, as_owner: AsyncClient, as_member: AsyncClient
) -> None:
    """Reopening is continuing the work, not overriding somebody's decision, so
    it sits with start/end rather than with cancel."""
    visit = (await _create(as_owner, collab_hunt)).json()
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "start"})
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "end"})

    reopened = await as_member.patch(f"/v1/visits/{visit['id']}", json={"action": "reopen"})
    assert reopened.status_code == 200, reopened.text
    assert reopened.json()["state"] == "in_progress"


@pytest.mark.asyncio
async def test_reopening_a_visit_that_never_ended_is_refused(
    collab_hunt, as_owner: AsyncClient
) -> None:
    visit = (await _create(as_owner, collab_hunt)).json()
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "start"})
    response = await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "reopen"})
    assert response.status_code == 409
    assert response.json()["code"] == "invalid_visit_transition"


@pytest.mark.asyncio
async def test_a_cancelled_visit_must_be_reinstated_before_reopening(
    collab_hunt, as_owner: AsyncClient
) -> None:
    """Cancellation outranks everything; reopening must not sneak past it."""
    visit = (await _create(as_owner, collab_hunt)).json()
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "start"})
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "end"})
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "cancel"})

    refused = await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "reopen"})
    assert refused.status_code == 409
    assert refused.json()["code"] == "invalid_visit_transition"


@pytest.mark.asyncio
async def test_reopening_never_re_resolves_the_frozen_template(
    collab_hunt, as_owner: AsyncClient, db_pool
) -> None:
    """`template_version` is immutable, so a finished tour cannot change meaning."""
    visit = (await _create(as_owner, collab_hunt)).json()
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "start"})
    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "end"})
    before = await db_pool.fetchval(
        "select template_version from visits where id = $1", visit["id"]
    )

    await as_owner.patch(f"/v1/visits/{visit['id']}", json={"action": "reopen"})
    after = await db_pool.fetchval("select template_version from visits where id = $1", visit["id"])
    assert after == before
