-- Generated Catalog sync from shared/src/manzil_shared/catalog.py.
-- P3-SC3 first Property/Unit type tranche; idempotent on hosted and local databases.

insert into criteria_catalog
  (key, label, category, domain, fact_scope, value_schema, claim_value_schema, default_options, extraction_hint, requires_tool, refresh_class, escalation_policy, conflict_policy)
values
  ('pool', 'Pool', 'property', 'rent', 'property', '{"type": "string", "enum": ["indoor", "outdoor", "indoor_and_outdoor", "unspecified", "none"]}'::jsonb, null, '[{"match": {"op": "eq", "value": "indoor_and_outdoor"}, "delta": 0.5}, {"match": {"op": "in", "value": ["indoor", "outdoor"]}, "delta": 0.25}, {"match": {"op": "eq", "value": "unspecified"}, "delta": 0.25}, {"match": {"op": "eq", "value": "none"}, "delta": 0.0}]'::jsonb, 'Shared Property pool facilities only: indoor, outdoor, both, unspecified type, or explicitly none. Do not infer private-unit pools.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('fitness_center', 'Fitness center or gym', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.5}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only for an on-site resident fitness center or gym.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('clubhouse', 'Clubhouse', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when the Property advertises a resident clubhouse.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('emergency_maintenance', 'Emergency maintenance', 'property', 'rent', 'property', '{"type": "string", "enum": ["emergency_service", "24_hour_emergency", "none"]}'::jsonb, null, '[{"match": {"op": "eq", "value": "24_hour_emergency"}, "delta": 0.5}, {"match": {"op": "eq", "value": "emergency_service"}, "delta": 0.25}, {"match": {"op": "eq", "value": "none"}, "delta": 0.0}]'::jsonb, '24_hour_emergency only when 24-hour emergency maintenance is explicit; emergency_service for emergency maintenance without a 24-hour promise; none only when explicitly unavailable.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('maintenance_on_site', 'Maintenance on site', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when on-site maintenance staff or service is advertised.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('management_on_site', 'Management on site', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when on-site Property management is advertised.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('online_payments', 'Online payments', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when online rent payments are explicit. A generic resident portal alone is display evidence and does not prove this capability.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('online_maintenance_requests', 'Online maintenance requests', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when residents can submit maintenance requests online. A generic resident portal alone is display evidence and does not prove this capability.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('package_handling', 'Package handling', 'property', 'rent', 'property', '{"type": "string", "enum": ["locker", "secured_room", "office", "unsecured_area", "none"]}'::jsonb, null, '[{"match": {"op": "eq", "value": "locker"}, "delta": 0.5}, {"match": {"op": "eq", "value": "secured_room"}, "delta": 0.25}, {"match": {"op": "eq", "value": "office"}, "delta": 0.1}, {"match": {"op": "eq", "value": "unsecured_area"}, "delta": 0.0}, {"match": {"op": "eq", "value": "none"}, "delta": 0.0}]'::jsonb, 'How resident packages are handled: dedicated locker, secured room, office receipt, unsecured area, or explicitly none.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred'),
  ('smoking_policy', 'Smoking policy', 'property', 'rent', 'property', '{"type": "string", "enum": ["smoke_free_property", "designated_areas_only", "permitted"]}'::jsonb, null, '[{"match": {"op": "eq", "value": "smoke_free_property"}, "delta": 0.5}, {"match": {"op": "eq", "value": "designated_areas_only"}, "delta": 0.0}, {"match": {"op": "eq", "value": "permitted"}, "delta": -0.5}]'::jsonb, 'Property-wide smoking policy: fully smoke-free, permitted only in designated areas, or generally permitted. Silence is unknown.', null, 'listing_details', 'decision_relevant', 'standard_ladder'),
  ('property_types', 'Property types', 'property', 'rent', 'property', '{"type": "array", "items": {"type": "string", "enum": ["apartment", "condo", "townhome", "duplex", "single_family", "loft", "other"]}, "minItems": 1, "uniqueItems": true}'::jsonb, null, '[{"match": {"op": "contains_any", "value": ["apartment", "condo", "townhome", "duplex", "single_family", "loft", "other"]}, "delta": 0.0}]'::jsonb, 'Every explicitly advertised Property type from the controlled vocabulary. Preserve multiple types; do not infer from architecture or a Floor Plan name.', null, 'listing_details', 'decision_relevant', 'standard_ladder'),
  ('unit_types', 'Unit types', 'unit', 'rent', 'floor_plan', '{"type": "array", "items": {"type": "string", "enum": ["apartment", "condo", "townhome", "duplex", "single_family", "loft", "other"]}, "minItems": 1, "uniqueItems": true}'::jsonb, null, '[{"match": {"op": "contains_any", "value": ["apartment", "condo", "townhome", "duplex", "single_family", "loft", "other"]}, "delta": 0.0}]'::jsonb, 'Every explicitly advertised type for the Floor Plan. Usually one value; preserve multiple types for a genuinely hybrid offering and do not infer from architecture.', null, 'listing_details', 'decision_relevant', 'standard_ladder'),
  ('internet_readiness', 'Internet readiness advertised', 'property', 'rent', 'property', '{"type": "boolean"}'::jsonb, null, '[{"match": {"op": "bool", "value": true}, "delta": 0.25}, {"match": {"op": "bool", "value": false}, "delta": 0.0}]'::jsonb, 'True only when the Source advertises general internet, high-speed internet, or fiber readiness for the Property. This does not verify provider serviceability, speed, Floor Plan coverage, or inclusion in rent; silence is unknown.', null, 'listing_details', 'available_sources_only', 'verified_positive_preferred')
on conflict (key) do update set
  label = excluded.label,
  category = excluded.category,
  domain = excluded.domain,
  fact_scope = excluded.fact_scope,
  value_schema = excluded.value_schema,
  claim_value_schema = excluded.claim_value_schema,
  default_options = excluded.default_options,
  extraction_hint = excluded.extraction_hint,
  requires_tool = excluded.requires_tool,
  refresh_class = excluded.refresh_class,
  escalation_policy = excluded.escalation_policy,
  conflict_policy = excluded.conflict_policy;
